return {
  {
    name = "Сложение",
    level = 1,
    task = "a + b = ?",
    limit = 10,
    tasksN = 6,
    tasksType = "task",
  },
  {
    name = "Сложение",
    level = 2,
    task = "a + b = ?",
    limit = 10,
    tasksN = 8,
    tasksType = "number",
  },
  {
    name = "Сложение",
    level = 3,
    task = "a + ? = b",
    limit = 10,
    tasksN = 9,
    tasksType = "task",
  },
  {
    name = "Сложение",
    level = 4,
    task = "a + ? = b",
    limit = 20,
    tasksN = 6,
    tasksType = "task",
  },
  {
    name = "Сложение",
    level = 5,
    task = "a + b = ?",
    limit = 50,
    tasksN = 9,
    tasksType = "task",
  },
  {
    name = "Сложение",
    level = 6,
    task = "a + b = ?",
    limit = 50,
    tasksN = 9,
    tasksType = "number",
  },
  {
    name = "Сложение",
    level = 7,
    task = "a + b = ?",
    limit = 100,
    tasksN = 9,
    tasksType = "number",
  },
  {
    name = "Сложение",
    level = 8,
    task = "a + b = ?",
    limit = 100,
    tasksN = 11,
    tasksType = "task",
  },
  {
    name = "Сложение",
    level = 9,
    task = "a + b = ?",
    limit = 200,
    tasksN = 11,
    tasksType = "number",
  },
  {
    name = "Тест",
    level = 1,
    task = "a + ? = b",
    limit = 10,
    tasksN = 1,
    tasksType = "task",
  }
}